# Generated by Django 2.2.3 on 2019-07-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('departamentos', '0003_auto_20190727_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(help_text='Nome do departamento', max_length=70),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'empresa')},
        ),
    ]
